### ISSUE TITLE
Rich text field and @contentful/rich-text-react-renderer

### ISSUE THREAD

**Issue by petercherm** [marcolink/cf-content-types-generator-app#136]
Hi,
I have a quick question. I have a `Rich text` type field in my content model. The `cf-content-types-generator-app` is spitting out the type for this field as `CFRichTextTypes.Block | CFRichTextTypes.Inline`, but `documentToReactComponents` from `@contentful/rich-text-react-renderer` is expecting `CFRichTextTypes.Document`. It works when I change it manually, but I don't want to be manually fixing it every time I get the types when my content model changes. Am I missing something here?

Many thanks in advance,
Peter.

**Comment by marcolink** [comment]
@petercherm,

the latest version is now correctly typing as `Document`
